language: python
python:
 - "2.6"
 - "2.7"
before_install:
  - sudo add-apt-repository ppa:ultrafredde/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq task
  - sudo apt-get install -qq pandoc
  - task --version
  - pip install taskw
  - pip install mock
  - pip install unittest2
  - pip install megaplan
  - pip install jira-python
  - pip install pypandoc
  - pip install pyac
install: python setup.py install
script: nosetests -w tests
notifications:
    email: true
    irc:
        - "irc.freenode.net#threebean"
    on_success: change
    on_failure: always
